### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by erenarkangil** [aberke/lbs-data#5]
Hi Alex,

Congrats, great work ! I wonder if the dataset publicly available, couldn't find raw data referred in the article:

''e first 5-day workweek of May 2018, restricted to data points reported within the 3 counties surrounding Boston, Massachusetts (Middlesex, Norfolk, and Suffolk counties).''

Many thanks.

**Comment by aberke** [comment]
No, the raw data is not to be made publicly available.
Thanks!
